[workspace]
authors = ["Zhuofeng Wang <zhuofengwang2003@gmail.com>"]
channels = ["conda-forge"]
name = "staged-recipes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rattler-build = ">=0.42.1,<0.43"
yq = ">=3.4.3,<4"
jq = ">=1.7.1,<2"
